image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [ 669.33891,    0.     ,  606.22332,
            0.     ,  680.90506,  338.92249,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.389041, 0.156478, -0.006723, -0.000567, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 530.08478,    0.      ,  605.65348,    0.     ,
            0.     ,   594.69562,  326.29526,    0.     ,
            0.     ,    0.      ,    1.     ,    0.     ]