image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [ 1328.81184,     0.     ,   639.23614,
             0.     ,  1199.94327,   347.70536,
             0.     ,     0.     ,     1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.812601, 0.594715, 0.078625, 0.007583, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 1063.85547,     0.     ,   654.32109,     0.     ,
             0.     ,  1088.67358,   381.39644,     0.     ,
             0.     ,     0.     ,     1.     ,     0.     ]
