image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [ 856.70953,    0.     ,  588.80171,
            0.     ,  760.19011,  144.3627 ,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.513691, 0.092793, 0.110949, 0.007925, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 3294.68872,    0.     ,  989.31874,    0.     ,
            0.     , -6644.62402, -871.14773,    0.     ,
            0.     ,    0.      ,    1.     ,    0.     ]