image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [ 1145.49672,     0.     ,   652.11745,
             0.     ,  1071.78084,   360.20381,
             0.     ,     0.     ,     1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.724331, 0.356488, -0.000768, 0.001143, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 772.63806,    0.     ,  667.74945,    0.     ,
            0.     ,  971.10785,  359.33436,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
