# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'collisionWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(716, 596)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelR = QtWidgets.QLabel(self.centralwidget)
        self.labelR.setGeometry(QtCore.QRect(40, 30, 140, 25))
        self.labelR.setObjectName("labelR")
        self.RegionIDgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.RegionIDgroupBox.setGeometry(QtCore.QRect(40, 60, 631, 61))
        self.RegionIDgroupBox.setTitle("")
        self.RegionIDgroupBox.setObjectName("RegionIDgroupBox")
        self.checkBox0 = QtWidgets.QCheckBox(self.RegionIDgroupBox)
        self.checkBox0.setGeometry(QtCore.QRect(20, 30, 80, 25))
        self.checkBox0.setObjectName("checkBox0")
        self.checkBox1 = QtWidgets.QCheckBox(self.RegionIDgroupBox)
        self.checkBox1.setGeometry(QtCore.QRect(100, 30, 80, 25))
        self.checkBox1.setObjectName("checkBox1")
        self.checkBox2 = QtWidgets.QCheckBox(self.RegionIDgroupBox)
        self.checkBox2.setGeometry(QtCore.QRect(180, 30, 80, 25))
        self.checkBox2.setObjectName("checkBox2")
        self.checkBox3 = QtWidgets.QCheckBox(self.RegionIDgroupBox)
        self.checkBox3.setGeometry(QtCore.QRect(260, 30, 80, 25))
        self.checkBox3.setObjectName("checkBox3")
        self.checkBox4 = QtWidgets.QCheckBox(self.RegionIDgroupBox)
        self.checkBox4.setGeometry(QtCore.QRect(340, 30, 80, 25))
        self.checkBox4.setObjectName("checkBox4")
        self.checkBox5 = QtWidgets.QCheckBox(self.RegionIDgroupBox)
        self.checkBox5.setGeometry(QtCore.QRect(420, 30, 80, 25))
        self.checkBox5.setObjectName("checkBox5")
        self.checkBox6 = QtWidgets.QCheckBox(self.RegionIDgroupBox)
        self.checkBox6.setGeometry(QtCore.QRect(500, 30, 80, 25))
        self.checkBox6.setObjectName("checkBox6")
        self.checkBox7 = QtWidgets.QCheckBox(self.RegionIDgroupBox)
        self.checkBox7.setGeometry(QtCore.QRect(580, 30, 80, 25))
        self.checkBox7.setObjectName("checkBox7")
        self.checkBox8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox8.setGeometry(QtCore.QRect(140, 30, 121, 21))
        self.checkBox8.setObjectName("checkBox8")
        self.checkBox9 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox9.setGeometry(QtCore.QRect(40, 170, 151, 21))
        self.checkBox9.setObjectName("checkBox9")
        self.CoordinategroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.CoordinategroupBox.setGeometry(QtCore.QRect(40, 200, 611, 291))
        self.CoordinategroupBox.setTitle("")
        self.CoordinategroupBox.setObjectName("CoordinategroupBox")
        self.label1X = QtWidgets.QLabel(self.CoordinategroupBox)
        self.label1X.setGeometry(QtCore.QRect(30, 50, 140, 25))
        self.label1X.setObjectName("label1X")
        self.label1Y = QtWidgets.QLabel(self.CoordinategroupBox)
        self.label1Y.setGeometry(QtCore.QRect(30, 110, 140, 25))
        self.label1Y.setObjectName("label1Y")
        self.label2X = QtWidgets.QLabel(self.CoordinategroupBox)
        self.label2X.setGeometry(QtCore.QRect(30, 170, 140, 25))
        self.label2X.setObjectName("label2X")
        self.label2Y = QtWidgets.QLabel(self.CoordinategroupBox)
        self.label2Y.setGeometry(QtCore.QRect(30, 230, 140, 25))
        self.label2Y.setObjectName("label2Y")
        self.label0 = QtWidgets.QLabel(self.CoordinategroupBox)
        self.label0.setGeometry(QtCore.QRect(170, 50, 140, 25))
        self.label0.setObjectName("label0")
        self.maxSlider0 = QtWidgets.QSlider(self.CoordinategroupBox)
        self.maxSlider0.setGeometry(QtCore.QRect(370, 50, 141, 25))
        self.maxSlider0.setMaximum(8191)
        self.maxSlider0.setOrientation(QtCore.Qt.Horizontal)
        self.maxSlider0.setObjectName("maxSlider0")
        self.maxSlider1 = QtWidgets.QSlider(self.CoordinategroupBox)
        self.maxSlider1.setGeometry(QtCore.QRect(370, 110, 141, 25))
        self.maxSlider1.setMaximum(2047)
        self.maxSlider1.setOrientation(QtCore.Qt.Horizontal)
        self.maxSlider1.setObjectName("maxSlider1")
        self.label1 = QtWidgets.QLabel(self.CoordinategroupBox)
        self.label1.setGeometry(QtCore.QRect(170, 110, 140, 25))
        self.label1.setObjectName("label1")
        self.maxSlider2 = QtWidgets.QSlider(self.CoordinategroupBox)
        self.maxSlider2.setGeometry(QtCore.QRect(370, 170, 141, 25))
        self.maxSlider2.setMaximum(8191)
        self.maxSlider2.setProperty("value", 8191)
        self.maxSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.maxSlider2.setObjectName("maxSlider2")
        self.label2 = QtWidgets.QLabel(self.CoordinategroupBox)
        self.label2.setGeometry(QtCore.QRect(170, 170, 140, 25))
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(self.CoordinategroupBox)
        self.label3.setGeometry(QtCore.QRect(170, 230, 140, 25))
        self.label3.setObjectName("label3")
        self.maxSlider3 = QtWidgets.QSlider(self.CoordinategroupBox)
        self.maxSlider3.setGeometry(QtCore.QRect(370, 230, 141, 25))
        self.maxSlider3.setMaximum(2047)
        self.maxSlider3.setProperty("value", 2047)
        self.maxSlider3.setOrientation(QtCore.Qt.Horizontal)
        self.maxSlider3.setObjectName("maxSlider3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(370, 530, 191, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(580, 530, 89, 25))
        self.sendButton.setObjectName("sendButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelR.setText(_translate("MainWindow", "RegionID"))
        self.checkBox0.setText(_translate("MainWindow", "0"))
        self.checkBox1.setText(_translate("MainWindow", "1"))
        self.checkBox2.setText(_translate("MainWindow", "2"))
        self.checkBox3.setText(_translate("MainWindow", "3"))
        self.checkBox4.setText(_translate("MainWindow", "4"))
        self.checkBox5.setText(_translate("MainWindow", "5"))
        self.checkBox6.setText(_translate("MainWindow", "6"))
        self.checkBox7.setText(_translate("MainWindow", "7"))
        self.checkBox8.setText(_translate("MainWindow", "Activation"))
        self.checkBox9.setText(_translate("MainWindow", "Coordinates_valid"))
        self.label1X.setText(_translate("MainWindow", "Point1X"))
        self.label1Y.setText(_translate("MainWindow", "Point1Y"))
        self.label2X.setText(_translate("MainWindow", "Point2X"))
        self.label2Y.setText(_translate("MainWindow", "Point2Y"))
        self.label0.setText(_translate("MainWindow", "-500"))
        self.label1.setText(_translate("MainWindow", "-204.6"))
        self.label2.setText(_translate("MainWindow", "1138.2"))
        self.label3.setText(_translate("MainWindow", "204.8"))
        self.lineEdit.setText(_translate("MainWindow", "can0"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "can name"))
        self.sendButton.setText(_translate("MainWindow", "PushButton"))

