# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_designer/filterWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 724)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox0 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox0.setGeometry(QtCore.QRect(10, 10, 80, 25))
        self.checkBox0.setObjectName("checkBox0")
        self.checkBox3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox3.setGeometry(QtCore.QRect(10, 130, 110, 25))
        self.checkBox3.setObjectName("checkBox3")
        self.checkBox9 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox9.setGeometry(QtCore.QRect(10, 370, 34, 23))
        self.checkBox9.setObjectName("checkBox9")
        self.checkBox1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox1.setGeometry(QtCore.QRect(10, 50, 81, 25))
        self.checkBox1.setObjectName("checkBox1")
        self.checkBox2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox2.setGeometry(QtCore.QRect(10, 90, 81, 25))
        self.checkBox2.setObjectName("checkBox2")
        self.checkBox4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox4.setGeometry(QtCore.QRect(10, 170, 100, 25))
        self.checkBox4.setObjectName("checkBox4")
        self.checkBox5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox5.setGeometry(QtCore.QRect(10, 210, 52, 23))
        self.checkBox5.setObjectName("checkBox5")
        self.checkBox6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox6.setGeometry(QtCore.QRect(10, 250, 80, 25))
        self.checkBox6.setObjectName("checkBox6")
        self.checkBox7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox7.setGeometry(QtCore.QRect(10, 290, 52, 23))
        self.checkBox7.setObjectName("checkBox7")
        self.checkBox8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox8.setGeometry(QtCore.QRect(10, 330, 97, 25))
        self.checkBox8.setObjectName("checkBox8")
        self.checkBoxA = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxA.setGeometry(QtCore.QRect(10, 410, 36, 23))
        self.checkBoxA.setObjectName("checkBoxA")
        self.checkBoxB = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxB.setGeometry(QtCore.QRect(10, 450, 108, 25))
        self.checkBoxB.setObjectName("checkBoxB")
        self.checkBoxC = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxC.setGeometry(QtCore.QRect(10, 490, 102, 25))
        self.checkBoxC.setObjectName("checkBoxC")
        self.checkBoxD = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxD.setGeometry(QtCore.QRect(10, 530, 108, 25))
        self.checkBoxD.setObjectName("checkBoxD")
        self.checkBoxE = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxE.setGeometry(QtCore.QRect(10, 570, 92, 25))
        self.checkBoxE.setObjectName("checkBoxE")
        self.label0 = QtWidgets.QLabel(self.centralwidget)
        self.label0.setGeometry(QtCore.QRect(220, 10, 140, 25))
        self.label0.setObjectName("label0")
        self.comboBox0 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox0.setGeometry(QtCore.QRect(130, 10, 80, 25))
        self.comboBox0.setObjectName("comboBox0")
        self.comboBox0.addItem("")
        self.comboBox0.addItem("")
        self.comboBox1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox1.setGeometry(QtCore.QRect(130, 50, 80, 25))
        self.comboBox1.setObjectName("comboBox1")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox2.setGeometry(QtCore.QRect(130, 90, 80, 25))
        self.comboBox2.setObjectName("comboBox2")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox3.setGeometry(QtCore.QRect(130, 130, 80, 25))
        self.comboBox3.setObjectName("comboBox3")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.comboBox4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox4.setGeometry(QtCore.QRect(130, 170, 80, 25))
        self.comboBox4.setObjectName("comboBox4")
        self.comboBox4.addItem("")
        self.comboBox4.addItem("")
        self.comboBox5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox5.setGeometry(QtCore.QRect(130, 210, 80, 25))
        self.comboBox5.setObjectName("comboBox5")
        self.comboBox5.addItem("")
        self.comboBox5.addItem("")
        self.comboBox6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox6.setGeometry(QtCore.QRect(130, 250, 80, 25))
        self.comboBox6.setObjectName("comboBox6")
        self.comboBox6.addItem("")
        self.comboBox6.addItem("")
        self.comboBox7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox7.setGeometry(QtCore.QRect(130, 290, 80, 25))
        self.comboBox7.setObjectName("comboBox7")
        self.comboBox7.addItem("")
        self.comboBox7.addItem("")
        self.comboBox8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox8.setGeometry(QtCore.QRect(130, 330, 80, 25))
        self.comboBox8.setObjectName("comboBox8")
        self.comboBox8.addItem("")
        self.comboBox8.addItem("")
        self.comboBox9 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox9.setGeometry(QtCore.QRect(130, 370, 80, 25))
        self.comboBox9.setObjectName("comboBox9")
        self.comboBox9.addItem("")
        self.comboBox9.addItem("")
        self.comboBoxA = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxA.setGeometry(QtCore.QRect(130, 410, 80, 25))
        self.comboBoxA.setObjectName("comboBoxA")
        self.comboBoxA.addItem("")
        self.comboBoxA.addItem("")
        self.comboBoxB = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxB.setGeometry(QtCore.QRect(130, 450, 80, 25))
        self.comboBoxB.setObjectName("comboBoxB")
        self.comboBoxB.addItem("")
        self.comboBoxB.addItem("")
        self.comboBoxC = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxC.setGeometry(QtCore.QRect(130, 490, 80, 25))
        self.comboBoxC.setObjectName("comboBoxC")
        self.comboBoxC.addItem("")
        self.comboBoxC.addItem("")
        self.comboBoxD = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxD.setGeometry(QtCore.QRect(130, 530, 80, 25))
        self.comboBoxD.setObjectName("comboBoxD")
        self.comboBoxD.addItem("")
        self.comboBoxD.addItem("")
        self.comboBoxE = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxE.setGeometry(QtCore.QRect(130, 570, 80, 25))
        self.comboBoxE.setObjectName("comboBoxE")
        self.comboBoxE.addItem("")
        self.comboBoxE.addItem("")
        self.comboBoxF = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxF.setGeometry(QtCore.QRect(130, 610, 80, 25))
        self.comboBoxF.setObjectName("comboBoxF")
        self.comboBoxF.addItem("")
        self.comboBoxF.addItem("")
        self.minSlider1 = QtWidgets.QSlider(self.centralwidget)
        self.minSlider1.setGeometry(QtCore.QRect(370, 50, 141, 25))
        self.minSlider1.setMaximum(4095)
        self.minSlider1.setOrientation(QtCore.Qt.Horizontal)
        self.minSlider1.setObjectName("minSlider1")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(220, 50, 140, 25))
        self.label1.setObjectName("label1")
        self.minSlider2 = QtWidgets.QSlider(self.centralwidget)
        self.minSlider2.setGeometry(QtCore.QRect(370, 90, 141, 25))
        self.minSlider2.setMaximum(4095)
        self.minSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.minSlider2.setObjectName("minSlider2")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(220, 90, 140, 25))
        self.label2.setObjectName("label2")
        self.minSlider3 = QtWidgets.QSlider(self.centralwidget)
        self.minSlider3.setGeometry(QtCore.QRect(370, 130, 141, 25))
        self.minSlider3.setMaximum(4095)
        self.minSlider3.setOrientation(QtCore.Qt.Horizontal)
        self.minSlider3.setObjectName("minSlider3")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(220, 130, 140, 25))
        self.label3.setObjectName("label3")
        self.minSlider4 = QtWidgets.QSlider(self.centralwidget)
        self.minSlider4.setGeometry(QtCore.QRect(370, 170, 141, 25))
        self.minSlider4.setMaximum(4095)
        self.minSlider4.setOrientation(QtCore.Qt.Horizontal)
        self.minSlider4.setObjectName("minSlider4")
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(220, 170, 140, 25))
        self.label4.setObjectName("label4")
        self.minSlider5 = QtWidgets.QSlider(self.centralwidget)
        self.minSlider5.setGeometry(QtCore.QRect(370, 210, 141, 25))
        self.minSlider5.setMaximum(4095)
        self.minSlider5.setOrientation(QtCore.Qt.Horizontal)
        self.minSlider5.setObjectName("minSlider5")
        self.label5 = QtWidgets.QLabel(self.centralwidget)
        self.label5.setGeometry(QtCore.QRect(220, 210, 140, 25))
        self.label5.setObjectName("label5")
        self.minSlider6 = QtWidgets.QSlider(self.centralwidget)
        self.minSlider6.setGeometry(QtCore.QRect(370, 250, 141, 25))
        self.minSlider6.setMaximum(4095)
        self.minSlider6.setOrientation(QtCore.Qt.Horizontal)
        self.minSlider6.setObjectName("minSlider6")
        self.label6 = QtWidgets.QLabel(self.centralwidget)
        self.label6.setGeometry(QtCore.QRect(220, 250, 140, 25))
        self.label6.setObjectName("label6")
        self.minSlider7 = QtWidgets.QSlider(self.centralwidget)
        self.minSlider7.setGeometry(QtCore.QRect(370, 290, 141, 25))
        self.minSlider7.setMaximum(4095)
        self.minSlider7.setOrientation(QtCore.Qt.Horizontal)
        self.minSlider7.setObjectName("minSlider7")
        self.label7 = QtWidgets.QLabel(self.centralwidget)
        self.label7.setGeometry(QtCore.QRect(220, 290, 140, 25))
        self.label7.setObjectName("label7")
        self.minSlider8 = QtWidgets.QSlider(self.centralwidget)
        self.minSlider8.setGeometry(QtCore.QRect(370, 330, 141, 25))
        self.minSlider8.setMaximum(4095)
        self.minSlider8.setOrientation(QtCore.Qt.Horizontal)
        self.minSlider8.setObjectName("minSlider8")
        self.label8 = QtWidgets.QLabel(self.centralwidget)
        self.label8.setGeometry(QtCore.QRect(220, 330, 140, 25))
        self.label8.setObjectName("label8")
        self.minSlider9 = QtWidgets.QSlider(self.centralwidget)
        self.minSlider9.setGeometry(QtCore.QRect(370, 370, 141, 25))
        self.minSlider9.setMaximum(4095)
        self.minSlider9.setOrientation(QtCore.Qt.Horizontal)
        self.minSlider9.setObjectName("minSlider9")
        self.label9 = QtWidgets.QLabel(self.centralwidget)
        self.label9.setGeometry(QtCore.QRect(220, 370, 140, 25))
        self.label9.setObjectName("label9")
        self.minSliderA = QtWidgets.QSlider(self.centralwidget)
        self.minSliderA.setGeometry(QtCore.QRect(370, 410, 141, 25))
        self.minSliderA.setMaximum(4095)
        self.minSliderA.setOrientation(QtCore.Qt.Horizontal)
        self.minSliderA.setObjectName("minSliderA")
        self.labelA = QtWidgets.QLabel(self.centralwidget)
        self.labelA.setGeometry(QtCore.QRect(220, 410, 140, 25))
        self.labelA.setObjectName("labelA")
        self.minSliderB = QtWidgets.QSlider(self.centralwidget)
        self.minSliderB.setGeometry(QtCore.QRect(370, 450, 141, 25))
        self.minSliderB.setMaximum(4095)
        self.minSliderB.setOrientation(QtCore.Qt.Horizontal)
        self.minSliderB.setObjectName("minSliderB")
        self.labelB = QtWidgets.QLabel(self.centralwidget)
        self.labelB.setGeometry(QtCore.QRect(220, 450, 140, 25))
        self.labelB.setObjectName("labelB")
        self.minSliderC = QtWidgets.QSlider(self.centralwidget)
        self.minSliderC.setGeometry(QtCore.QRect(370, 490, 141, 25))
        self.minSliderC.setMaximum(4095)
        self.minSliderC.setOrientation(QtCore.Qt.Horizontal)
        self.minSliderC.setObjectName("minSliderC")
        self.labelC = QtWidgets.QLabel(self.centralwidget)
        self.labelC.setGeometry(QtCore.QRect(220, 490, 140, 25))
        self.labelC.setObjectName("labelC")
        self.minSliderD = QtWidgets.QSlider(self.centralwidget)
        self.minSliderD.setGeometry(QtCore.QRect(370, 530, 141, 25))
        self.minSliderD.setMaximum(4095)
        self.minSliderD.setOrientation(QtCore.Qt.Horizontal)
        self.minSliderD.setObjectName("minSliderD")
        self.labelD = QtWidgets.QLabel(self.centralwidget)
        self.labelD.setGeometry(QtCore.QRect(220, 530, 140, 25))
        self.labelD.setObjectName("labelD")
        self.minSliderE = QtWidgets.QSlider(self.centralwidget)
        self.minSliderE.setGeometry(QtCore.QRect(370, 570, 141, 25))
        self.minSliderE.setMaximum(4095)
        self.minSliderE.setOrientation(QtCore.Qt.Horizontal)
        self.minSliderE.setObjectName("minSliderE")
        self.labelE = QtWidgets.QLabel(self.centralwidget)
        self.labelE.setGeometry(QtCore.QRect(220, 570, 140, 25))
        self.labelE.setObjectName("labelE")
        self.labelF = QtWidgets.QLabel(self.centralwidget)
        self.labelF.setGeometry(QtCore.QRect(220, 610, 140, 25))
        self.labelF.setObjectName("labelF")
        self.maxSlider0 = QtWidgets.QSlider(self.centralwidget)
        self.maxSlider0.setGeometry(QtCore.QRect(530, 10, 141, 25))
        self.maxSlider0.setMaximum(4095)
        self.maxSlider0.setProperty("value", 4095)
        self.maxSlider0.setOrientation(QtCore.Qt.Horizontal)
        self.maxSlider0.setObjectName("maxSlider0")
        self.maxSlider1 = QtWidgets.QSlider(self.centralwidget)
        self.maxSlider1.setGeometry(QtCore.QRect(530, 50, 141, 25))
        self.maxSlider1.setMaximum(4095)
        self.maxSlider1.setProperty("value", 4095)
        self.maxSlider1.setOrientation(QtCore.Qt.Horizontal)
        self.maxSlider1.setObjectName("maxSlider1")
        self.maxSliderD = QtWidgets.QSlider(self.centralwidget)
        self.maxSliderD.setGeometry(QtCore.QRect(530, 530, 141, 25))
        self.maxSliderD.setMaximum(4095)
        self.maxSliderD.setProperty("value", 4095)
        self.maxSliderD.setOrientation(QtCore.Qt.Horizontal)
        self.maxSliderD.setObjectName("maxSliderD")
        self.maxSlider6 = QtWidgets.QSlider(self.centralwidget)
        self.maxSlider6.setGeometry(QtCore.QRect(530, 250, 141, 25))
        self.maxSlider6.setMaximum(4095)
        self.maxSlider6.setProperty("value", 4095)
        self.maxSlider6.setOrientation(QtCore.Qt.Horizontal)
        self.maxSlider6.setObjectName("maxSlider6")
        self.maxSliderC = QtWidgets.QSlider(self.centralwidget)
        self.maxSliderC.setGeometry(QtCore.QRect(530, 490, 141, 25))
        self.maxSliderC.setMaximum(4095)
        self.maxSliderC.setProperty("value", 4095)
        self.maxSliderC.setOrientation(QtCore.Qt.Horizontal)
        self.maxSliderC.setObjectName("maxSliderC")
        self.maxSlider3 = QtWidgets.QSlider(self.centralwidget)
        self.maxSlider3.setGeometry(QtCore.QRect(530, 130, 141, 25))
        self.maxSlider3.setMaximum(4095)
        self.maxSlider3.setProperty("value", 4095)
        self.maxSlider3.setOrientation(QtCore.Qt.Horizontal)
        self.maxSlider3.setObjectName("maxSlider3")
        self.maxSlider4 = QtWidgets.QSlider(self.centralwidget)
        self.maxSlider4.setGeometry(QtCore.QRect(530, 170, 141, 25))
        self.maxSlider4.setMaximum(4095)
        self.maxSlider4.setProperty("value", 4095)
        self.maxSlider4.setOrientation(QtCore.Qt.Horizontal)
        self.maxSlider4.setObjectName("maxSlider4")
        self.maxSlider7 = QtWidgets.QSlider(self.centralwidget)
        self.maxSlider7.setGeometry(QtCore.QRect(530, 290, 141, 25))
        self.maxSlider7.setMaximum(4095)
        self.maxSlider7.setProperty("value", 4095)
        self.maxSlider7.setOrientation(QtCore.Qt.Horizontal)
        self.maxSlider7.setObjectName("maxSlider7")
        self.maxSliderE = QtWidgets.QSlider(self.centralwidget)
        self.maxSliderE.setGeometry(QtCore.QRect(530, 570, 141, 25))
        self.maxSliderE.setMaximum(4095)
        self.maxSliderE.setProperty("value", 4095)
        self.maxSliderE.setOrientation(QtCore.Qt.Horizontal)
        self.maxSliderE.setObjectName("maxSliderE")
        self.maxSliderF = QtWidgets.QSlider(self.centralwidget)
        self.maxSliderF.setGeometry(QtCore.QRect(530, 610, 141, 25))
        self.maxSliderF.setMaximum(4095)
        self.maxSliderF.setProperty("value", 4095)
        self.maxSliderF.setOrientation(QtCore.Qt.Horizontal)
        self.maxSliderF.setObjectName("maxSliderF")
        self.maxSliderA = QtWidgets.QSlider(self.centralwidget)
        self.maxSliderA.setGeometry(QtCore.QRect(530, 410, 141, 25))
        self.maxSliderA.setMaximum(4095)
        self.maxSliderA.setProperty("value", 4095)
        self.maxSliderA.setOrientation(QtCore.Qt.Horizontal)
        self.maxSliderA.setObjectName("maxSliderA")
        self.maxSlider2 = QtWidgets.QSlider(self.centralwidget)
        self.maxSlider2.setGeometry(QtCore.QRect(530, 90, 141, 25))
        self.maxSlider2.setMaximum(4095)
        self.maxSlider2.setProperty("value", 4095)
        self.maxSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.maxSlider2.setObjectName("maxSlider2")
        self.maxSlider5 = QtWidgets.QSlider(self.centralwidget)
        self.maxSlider5.setGeometry(QtCore.QRect(530, 210, 141, 25))
        self.maxSlider5.setMaximum(4095)
        self.maxSlider5.setProperty("value", 4095)
        self.maxSlider5.setOrientation(QtCore.Qt.Horizontal)
        self.maxSlider5.setObjectName("maxSlider5")
        self.maxSlider8 = QtWidgets.QSlider(self.centralwidget)
        self.maxSlider8.setGeometry(QtCore.QRect(530, 330, 141, 25))
        self.maxSlider8.setMaximum(4095)
        self.maxSlider8.setProperty("value", 4095)
        self.maxSlider8.setOrientation(QtCore.Qt.Horizontal)
        self.maxSlider8.setObjectName("maxSlider8")
        self.maxSliderB = QtWidgets.QSlider(self.centralwidget)
        self.maxSliderB.setGeometry(QtCore.QRect(530, 450, 141, 25))
        self.maxSliderB.setMaximum(4095)
        self.maxSliderB.setProperty("value", 4095)
        self.maxSliderB.setOrientation(QtCore.Qt.Horizontal)
        self.maxSliderB.setObjectName("maxSliderB")
        self.maxSlider9 = QtWidgets.QSlider(self.centralwidget)
        self.maxSlider9.setGeometry(QtCore.QRect(530, 370, 141, 25))
        self.maxSlider9.setMaximum(4095)
        self.maxSlider9.setProperty("value", 4095)
        self.maxSlider9.setOrientation(QtCore.Qt.Horizontal)
        self.maxSlider9.setObjectName("maxSlider9")
        self.radioButton_cluster = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_cluster.setGeometry(QtCore.QRect(10, 670, 91, 23))
        self.radioButton_cluster.setObjectName("radioButton_cluster")
        self.radioButton_object = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_object.setGeometry(QtCore.QRect(110, 670, 101, 23))
        self.radioButton_object.setChecked(True)
        self.radioButton_object.setObjectName("radioButton_object")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(372, 670, 191, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(580, 670, 89, 25))
        self.sendButton.setObjectName("sendButton")
        self.checkBoxF = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxF.setGeometry(QtCore.QRect(10, 610, 60, 23))
        self.checkBoxF.setObjectName("checkBoxF")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Set ARS408 message #202"))
        self.checkBox0.setText(_translate("MainWindow", "N of Obj"))
        self.checkBox3.setText(_translate("MainWindow", "Vrel Oncome"))
        self.checkBox9.setText(_translate("MainWindow", "Y"))
        self.checkBox1.setText(_translate("MainWindow", "Distance"))
        self.checkBox2.setText(_translate("MainWindow", "Azimuth"))
        self.checkBox4.setText(_translate("MainWindow", "Verl Depart"))
        self.checkBox5.setText(_translate("MainWindow", "RCS"))
        self.checkBox6.setText(_translate("MainWindow", "Lifetime"))
        self.checkBox7.setText(_translate("MainWindow", "Size"))
        self.checkBox8.setText(_translate("MainWindow", "Prob Exists"))
        self.checkBoxA.setText(_translate("MainWindow", "X"))
        self.checkBoxB.setText(_translate("MainWindow", "VY RightLeft"))
        self.checkBoxC.setText(_translate("MainWindow", "VX Oncome"))
        self.checkBoxD.setText(_translate("MainWindow", "VY LeftRight"))
        self.checkBoxE.setText(_translate("MainWindow", "VX Depart"))
        self.label0.setText(_translate("MainWindow", "0"))
        self.comboBox0.setItemText(0, _translate("MainWindow", "Inactive"))
        self.comboBox0.setItemText(1, _translate("MainWindow", "Active"))
        self.comboBox1.setItemText(0, _translate("MainWindow", "Inactive"))
        self.comboBox1.setItemText(1, _translate("MainWindow", "Active"))
        self.comboBox2.setItemText(0, _translate("MainWindow", "Inactive"))
        self.comboBox2.setItemText(1, _translate("MainWindow", "Active"))
        self.comboBox3.setItemText(0, _translate("MainWindow", "Inactive"))
        self.comboBox3.setItemText(1, _translate("MainWindow", "Active"))
        self.comboBox4.setItemText(0, _translate("MainWindow", "Inactive"))
        self.comboBox4.setItemText(1, _translate("MainWindow", "Active"))
        self.comboBox5.setItemText(0, _translate("MainWindow", "Inactive"))
        self.comboBox5.setItemText(1, _translate("MainWindow", "Active"))
        self.comboBox6.setItemText(0, _translate("MainWindow", "Inactive"))
        self.comboBox6.setItemText(1, _translate("MainWindow", "Active"))
        self.comboBox7.setItemText(0, _translate("MainWindow", "Inactive"))
        self.comboBox7.setItemText(1, _translate("MainWindow", "Active"))
        self.comboBox8.setItemText(0, _translate("MainWindow", "Inactive"))
        self.comboBox8.setItemText(1, _translate("MainWindow", "Active"))
        self.comboBox9.setItemText(0, _translate("MainWindow", "Inactive"))
        self.comboBox9.setItemText(1, _translate("MainWindow", "Active"))
        self.comboBoxA.setItemText(0, _translate("MainWindow", "Inactive"))
        self.comboBoxA.setItemText(1, _translate("MainWindow", "Active"))
        self.comboBoxB.setItemText(0, _translate("MainWindow", "Inactive"))
        self.comboBoxB.setItemText(1, _translate("MainWindow", "Active"))
        self.comboBoxC.setItemText(0, _translate("MainWindow", "Inactive"))
        self.comboBoxC.setItemText(1, _translate("MainWindow", "Active"))
        self.comboBoxD.setItemText(0, _translate("MainWindow", "Inactive"))
        self.comboBoxD.setItemText(1, _translate("MainWindow", "Active"))
        self.comboBoxE.setItemText(0, _translate("MainWindow", "Inactive"))
        self.comboBoxE.setItemText(1, _translate("MainWindow", "Active"))
        self.comboBoxF.setItemText(0, _translate("MainWindow", "Inactive"))
        self.comboBoxF.setItemText(1, _translate("MainWindow", "Active"))
        self.label1.setText(_translate("MainWindow", "0"))
        self.label2.setText(_translate("MainWindow", "0"))
        self.label3.setText(_translate("MainWindow", "0"))
        self.label4.setText(_translate("MainWindow", "0"))
        self.label5.setText(_translate("MainWindow", "0"))
        self.label6.setText(_translate("MainWindow", "0"))
        self.label7.setText(_translate("MainWindow", "0"))
        self.label8.setText(_translate("MainWindow", "0"))
        self.label9.setText(_translate("MainWindow", "0"))
        self.labelA.setText(_translate("MainWindow", "0"))
        self.labelB.setText(_translate("MainWindow", "0"))
        self.labelC.setText(_translate("MainWindow", "0"))
        self.labelD.setText(_translate("MainWindow", "0"))
        self.labelE.setText(_translate("MainWindow", "0"))
        self.labelF.setText(_translate("MainWindow", "0"))
        self.radioButton_cluster.setText(_translate("MainWindow", "Cluster"))
        self.radioButton_object.setText(_translate("MainWindow", "Object"))
        self.lineEdit.setText(_translate("MainWindow", "can0"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "can name"))
        self.sendButton.setText(_translate("MainWindow", "PushButton"))
        self.checkBoxF.setText(_translate("MainWindow", "Class"))

